baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Pippimotta'
theme='hugo-tufte'

[params]
  copyrightHolder = "kinoko"
  # Show the "Powered by Hugo-Tufte and Hugo." 
  showPoweredBy = true
  # Site wide kill switch
  hidedate = false
  # Uncomment for dark code blocks
  # codeBlocksDark = true

  # Common social website links, please comment the unused ones.
  ## (if your favorite one is not in the list, please head to the footer menu below and add an entry)
  ### Please note that some of the value below are only provided as an exemple, perhaps the computed isn't valid
  email = "lingyizh84@gmail.com"
  github = "pippimotta"
  mastodon = "g0v.social/@pippimotta"
  linkedin = "www.linkedin.com/in/lingyi-z/"

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fas fa-home la-lg'></i>"
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fas fa-book fa-lg'></i> "
  weight = -100 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fas fa-tags fa-lg'></i> "
  weight = -100 
  identifier = "categories"
  url = "/categories"
[[menu.nav]]
  name = "About"
  pre = "<i class='fas fa-ghost fa-lg '></i> "
  weight = -80 
  identifier = "about"
  url = "/about"

# Don't change the settings below
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # make the shortcodes work
  [markup.highlight]
      noClasses = false

pygmentsUseClasses = true
canonifyurls = true